apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: GATEWAY_DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GATEWAY_DATABASE_URL
             - name: EMAIL_SERVICE
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: EMAIL_SERVICE
             - name: EMAIL_USER
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: EMAIL_USER
             - name: EMAIL_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: EMAIL_PASSWORD
             - name: SWAGGER_ENABLED
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: SWAGGER_ENABLED
             - name: RESTORE_PASSWORD_CODE_EXPIRE_AFTER_MILISECONDS
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: RESTORE_PASSWORD_CODE_EXPIRE_AFTER_MILISECONDS
             - name: RESTORE_PASSWORD_CODE_LENGTH
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: RESTORE_PASSWORD_CODE_LENGTH
             - name: RECAPTCHA_SECRET_KEY
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: RECAPTCHA_SECRET_KEY
             - name: JWT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: JWT_SECRET
             - name: REFRESH_SECRET
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: REFRESH_SECRET
             - name: GOOGLE_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GOOGLE_CLIENT_ID
             - name: GOOGLE_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GOOGLE_CLIENT_SECRET
             - name: GOOGLE_REDIRECT_URI
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GOOGLE_REDIRECT_URI
             - name: GITHUB_CLIENT_ID
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GITHUB_CLIENT_ID
             - name: GITHUB_CALLBACK_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GITHUB_CALLBACK_URL
             - name: GLOBAL_PREFIX
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GLOBAL_PREFIX
             - name: RECAPTCHA_SITE_KEY
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: RECAPTCHA_SITE_KEY
             - name: EMAIL_CONFIRMATION_TOKEN_EXPIRE_AFTER_MILISECONDS
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: EMAIL_CONFIRMATION_TOKEN_EXPIRE_AFTER_MILISECONDS
             - name: FRONTED_PROVIDER
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: FRONTED_PROVIDER
             - name: GITHUB_CLIENT_SECRET
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: GITHUB_CLIENT_SECRET
             - name: PHOTO_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: PHOTO_SERVICE_HOST
             - name: PHOTO_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: PHOTO_SERVICE_PORT
             - name: PAYMENTS_SERVICE_HOST
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: PAYMENTS_SERVICE_HOST
             - name: PAYMENTS_SERVICE_PORT
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: PAYMENTS_SERVICE_PORT
             - name: RMQ_CONNECTION_STRING
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: RMQ_CONNECTION_STRING
             - name: NEXT_PUBLIC_MAIL_URL
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: NEXT_PUBLIC_MAIL_URL
             - name: PORT
               valueFrom:
                 secretKeyRef:
                   name: somegram-backend-production-config-secret
                   key: PORT
